### ISSUE TITLE
scheduler-lava should not quit on LAVA http errors

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-pipeline#357]
```
    today at 10:08:57 AM11/17/2023 08:08:57 AM UTC [INFO] Press Ctrl-C to stop.
    today at 10:19:13 AM11/17/2023 08:19:13 AM UTC [INFO] 65572200250c49d437a8521d lava-collabora qemu-x86 baseline-x86 12023380
    today at 10:19:13 AM11/17/2023 08:19:13 AM UTC [INFO] 65572201250c49d437a8521e lava-collabora minnowboard-turbot-E3826 baseline-x86 12023381
    today at 10:20:02 AM11/17/2023 08:20:02 AM UTC [INFO] 65572232250c49d437a85224 lava-collabora asus-cx9400-volteer baseline-x86-board 12023382
    today at 10:20:03 AM11/17/2023 08:20:03 AM UTC [INFO] 65572232250c49d437a85225 lava-collabora-staging dell-latitude-3445-7520c-skyrim baseline-x86-board-staging 547549
    today at 5:25:20 PM11/17/2023 03:25:20 PM UTC [INFO] 655785df250c49d437a85384 lava-collabora-staging qemu-x86 baseline-x86 547752
    today at 5:25:20 PM11/17/2023 03:25:20 PM UTC [ERROR] Traceback (most recent call last):
    today at 5:25:20 PM  File "/home/kernelci/pipeline/base.py", line 69, in run
    today at 5:25:20 PM    status = self._run(context)
    today at 5:25:20 PM  File "/home/kernelci/./pipeline/scheduler.py", line 102, in _run
    today at 5:25:20 PM    self._run_job(job, runtime, platform, input_node)
    today at 5:25:20 PM  File "/home/kernelci/./pipeline/scheduler.py", line 83, in _run_job
    today at 5:25:20 PM    running_job = runtime.submit(output_file)
    today at 5:25:20 PM  File "/usr/local/lib/python3.10/site-packages/kernelci-1.1-py3.10.egg/kernelci/runtime/lava.py", line 189, in submit
    today at 5:25:20 PM    job_id = self._submit(job)
    today at 5:25:20 PM  File "/usr/local/lib/python3.10/site-packages/kernelci-1.1-py3.10.egg/kernelci/runtime/lava.py", line 226, in _submit
    today at 5:25:20 PM    resp.raise_for_status()
    today at 5:25:20 PM  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    today at 5:25:20 PM    raise HTTPError(http_error_msg, response=self)
    today at 5:25:20 PMrequests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://staging.lava.collabora.dev/api/v0.2/jobs/?format=json&limit=256
    today at 5:25:20 PM
    today at 6:26:42 PMContainer stopped

```
Some retry mechanism and probably skip should be implemented.

**Comment by nuclearcat** [comment]
This issue already fixed
