### ISSUE TITLE
trigger: Fail on .git/index.lock, Another git process seems to be running in this repository

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-pipeline#361]
```
today at 10:07:39 AMFrom git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux
today at 10:07:39 AM * branch                      HEAD       -> FETCH_HEAD
today at 10:07:39 AM * [new tag]                   v6.7-rc3   -> v6.7-rc3
today at 10:07:40 AMfatal: Unable to create '/home/kernelci/data/src/linux/.git/index.lock': File exists.
today at 10:07:40 AM
today at 10:07:40 AMAnother git process seems to be running in this repository, e.g.
today at 10:07:40 AMan editor opened by 'git commit'. Please make sure all processes
today at 10:07:40 AMare terminated then try again. If it still fails, a git process
today at 10:07:40 AMmay have crashed in this repository earlier:
today at 10:07:40 AMremove the file manually to continue.
today at 10:07:40 AM11/27/2023 08:07:40 AM UTC [ERROR] Traceback (most recent call last):
today at 10:07:40 AM  File "/home/kernelci/pipeline/base.py", line 69, in run
today at 10:07:40 AM    status = self._run(context)
today at 10:07:40 AM  File "/home/kernelci/./pipeline/tarball.py", line 136, in _run
today at 10:07:40 AM    self._update_repo(build_config)
today at 10:07:40 AM  File "/home/kernelci/./pipeline/tarball.py", line 59, in _update_repo
today at 10:07:40 AM    kernelci.build.update_repo(config, self._kdir)
today at 10:07:40 AM  File "/usr/local/lib/python3.10/site-packages/kernelci-1.1-py3.10.egg/kernelci/build.py", line 163, in update_repo
today at 10:07:40 AM    shell_cmd("""
today at 10:07:40 AM  File "/usr/local/lib/python3.10/site-packages/kernelci-1.1-py3.10.egg/kernelci/__init__.py", line 29, in shell_cmd
today at 10:07:40 AM    return subprocess.check_output(cmd, shell=True).decode()
today at 10:07:40 AM  File "/usr/local/lib/python3.10/subprocess.py", line 420, in check_output
today at 10:07:40 AM    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
today at 10:07:40 AM  File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
today at 10:07:40 AM    raise CalledProcessError(retcode, process.args,
today at 10:07:40 AMsubprocess.CalledProcessError: Command '
today at 10:07:40 AMset -e
today at 10:07:40 AMcd /home/kernelci/data/src/linux
today at 10:07:40 AMgit reset --hard
today at 10:07:40 AMgit clean -fd
today at 10:07:40 AMgit checkout --detach kernelci/staging-mainline
today at 10:07:40 AM' returned non-zero exit status 128.
```

**Comment by gctucker** [comment]
How about fixing the tarball step properly by making it a job template like kbuild and kunit?  The only blocking issue there is about Kubernetes volumes to avoid having to do a full git clone every time.  I think that's part of the things that need to be defined in the production solution design.

**Comment by gctucker** [comment]
> Does it mark checkout node as completed or something like that?

If the tarball job fails, then the node should go to the Done state with result set to `fail` - like any other job.
