### ISSUE TITLE
BUG: `KeyError` exception while running `kver` job

### ISSUE THREAD

**Issue by JenySadadia** [kernelci/kernelci-pipeline#468]
The below error has been observed a few times on staging for `kver` job:
```
kernelci-pipeline-scheduler | Getting kernel source tree...
kernelci-pipeline-scheduler | Source directory: /tmp/kci/linux-kernelci-staging-stable-staging-stable-20240307.3
kernelci-pipeline-scheduler | Running job...
kernelci-pipeline-scheduler | Checking kernel revision
kernelci-pipeline-scheduler | Traceback (most recent call last):
kernelci-pipeline-scheduler |   File "/home/kernelci/data/output/tmpt22o569b/kver", line 208, in main
kernelci-pipeline-scheduler |     results = job.run()
kernelci-pipeline-scheduler |               ^^^^^^^^^
kernelci-pipeline-scheduler |   File "/home/kernelci/data/output/tmpt22o569b/kver", line 121, in run
kernelci-pipeline-scheduler |     return self._run(src_path)
kernelci-pipeline-scheduler |            ^^^^^^^^^^^^^^^^^^^
kernelci-pipeline-scheduler |   File "/home/kernelci/data/output/tmpt22o569b/kver", line 183, in _run
kernelci-pipeline-scheduler |     res = self._check_kver(makefile, kver)
kernelci-pipeline-scheduler |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kernelci-pipeline-scheduler |   File "/home/kernelci/data/output/tmpt22o569b/kver", line 172, in _check_kver
kernelci-pipeline-scheduler |     kver['sublevel'] == mkver['SUBLEVEL']
kernelci-pipeline-scheduler |     ~~~~^^^^^^^^^^^^
kernelci-pipeline-scheduler | KeyError: 'sublevel'
kernelci-pipeline-scheduler |
```

**Comment by JenySadadia** [comment]
Investigation summary:

The above error denotes an exception in `kver.jinja2` template from the below line:
```
return (
            kver['version'] == mkver['VERSION'] and
            kver['patchlevel'] == mkver['PATCHLEVEL'] and (
                not mkver['SUBLEVEL'] or
                kver['sublevel'] == mkver['SUBLEVEL']
            ) and (
                not mkver['EXTRAVERSION'] or
                kver['extra'].startswith(mkver['EXTRAVERSION'])
            )
        )
```
I wonder how this ends up in an exception as when `kver` dict doesn't include `sublevel` key, it means the version received from https://github.com/kernelci/kernelci-core/blob/main/kernelci/build.py#L207 doesn't have sublevel information. It means `mkver['SUBLEVEL]` (version information received from `Makefile`) should be `None` as well. But in this case, it implies the opposite.

I would need to gather more data to investigate this further.

**Comment by nuclearcat** [comment]
Closing as obsolete. The kver job, schedule, and template involved in this failure were removed from the current pipeline. See [821723d](https://github.com/kernelci/kernelci-pipeline/commit/821723d).
