### ISSUE TITLE
BUG: RuntimeError: Failed to render LAVA job template

### ISSUE THREAD

**Issue by JenySadadia** [kernelci/kernelci-pipeline#475]
Observed the below error for `scheduler-lava` service on staging:

```
today at 15:07:2503/15/2024 09:37:25 AM UTC [INFO] Listening for available checkout events
today at 15:07:2503/15/2024 09:37:25 AM UTC [INFO] Press Ctrl-C to stop.
today at 15:20:48DEBUG: <kernelci.config.job.Job object at 0x7f8c089a1cd0> <kernelci.runtime.lava.LAVA object at 0x7f8c09b249d0>
today at 15:20:4803/15/2024 09:50:48 AM UTC [ERROR] 65f419f75526417efee774c3 lava-collabora qemu-x86 baseline-x86 400 Client Error: Bad Request for url: https://lava.collabora.dev/api/v0.2/jobs/?format=json&limit=256
today at 15:20:48DEBUG: <kernelci.config.job.Job object at 0x7f8c089a1cd0> <kernelci.runtime.lava.LAVA object at 0x7f8c09b249d0>
today at 15:20:4803/15/2024 09:50:48 AM UTC [INFO] 65f419f85526417efee774c4 lava-collabora minnowboard-turbot-E3826 baseline-x86 13061187
today at 15:20:49DEBUG: <kernelci.config.job.Job object at 0x7f8c089a2350> <kernelci.runtime.lava.LAVA object at 0x7f8c09b249d0>
today at 15:20:4903/15/2024 09:50:49 AM UTC [INFO] 65f419f95526417efee774c5 lava-collabora acer-chromebox-cxi4-puff sleep 13061188
today at 15:22:49DEBUG: <kernelci.config.job.Job object at 0x7f8c089a1d90> <kernelci.runtime.lava.LAVA object at 0x7f8c09b249d0>
today at 15:22:4903/15/2024 09:52:49 AM UTC [INFO] 65f41a705526417efee774c7 lava-collabora mt8183-kukui-jacuzzi-juniper-sku16 baseline-arm64-chromeos-mediatek 13061191
today at 15:22:50DEBUG: <kernelci.config.job.Job object at 0x7f8c089a1d90> <kernelci.runtime.lava.LAVA object at 0x7f8c09b249d0>
today at 15:22:50Version 6.8 older than minimum version (6.9)
today at 15:22:50Not creating node due to platform rules for mt8186-corsola-steelix-sku131072
today at 15:22:50DEBUG: <kernelci.config.job.Job object at 0x7f8c089a1d90> <kernelci.runtime.lava.LAVA object at 0x7f8c09b249d0>
today at 15:22:5003/15/2024 09:52:50 AM UTC [INFO] 65f41a715526417efee774c8 lava-collabora mt8192-asurada-spherion-r0 baseline-arm64-chromeos-mediatek 13061192
today at 15:22:51DEBUG: <kernelci.config.job.Job object at 0x7f8c089a1d90> <kernelci.runtime.lava.LAVA object at 0x7f8c09b249d0>
today at 15:22:5103/15/2024 09:52:51 AM UTC [INFO] 65f41a725526417efee774c9 lava-collabora mt8195-cherry-tomato-r2 baseline-arm64-chromeos-mediatek 13061193
today at 15:22:52DEBUG: <kernelci.config.job.Job object at 0x7f8c089a06d0> <kernelci.runtime.lava.LAVA object at 0x7f8c09b249d0>
today at 15:22:5203/15/2024 09:52:52 AM UTC [INFO] 65f41a735526417efee774ca lava-collabora mt8183-kukui-jacuzzi-juniper-sku16 tast-basic-arm64-mediatek 13061194
today at 15:22:52DEBUG: <kernelci.config.job.Job object at 0x7f8c089a06d0> <kernelci.runtime.lava.LAVA object at 0x7f8c09b249d0>
today at 15:22:52Version 6.8 older than minimum version (6.9)
today at 15:22:52Not creating node due to platform rules for mt8186-corsola-steelix-sku131072
today at 15:22:52DEBUG: <kernelci.config.job.Job object at 0x7f8c089a06d0> <kernelci.runtime.lava.LAVA object at 0x7f8c09b249d0>
today at 15:22:5203/15/2024 09:52:52 AM UTC [ERROR] Traceback (most recent call last):
today at 15:22:52  File "/usr/local/lib/python3.11/site-packages/kernelci/runtime/lava.py", line 222, in generate
today at 15:22:52    rendered = template.render(params)
today at 15:22:52               ^^^^^^^^^^^^^^^^^^^^^^^
today at 15:22:52  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
today at 15:22:52    self.environment.handle_exception()
today at 15:22:52  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
today at 15:22:52    raise rewrite_traceback_stack(source=source)
today at 15:22:52  File "config/runtime/tast.jinja2", line 1, in top-level template code
today at 15:22:52    {%- set base_kurl = platform_config.params.flash_kernel.url %}
today at 15:22:52    ^^^^^^^^^^^^^^^^^^^^^^^^^
today at 15:22:52  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
today at 15:22:52    return getattr(obj, attribute)
today at 15:22:52           ^^^^^^^^^^^^^^^^^^^^^^^
today at 15:22:52jinja2.exceptions.UndefinedError: 'None' has no attribute 'flash_kernel'
today at 15:22:52
today at 15:22:52During handling of the above exception, another exception occurred:
today at 15:22:52
today at 15:22:52Traceback (most recent call last):
today at 15:22:52  File "/home/kernelci/pipeline/base.py", line 69, in run
today at 15:22:52    status = self._run(context)
today at 15:22:52             ^^^^^^^^^^^^^^^^^^
today at 15:22:52  File "/home/kernelci/./pipeline/scheduler.py", line 176, in _run
today at 15:22:52    self._run_job(job, runtime, platform, input_node)
today at 15:22:52  File "/home/kernelci/./pipeline/scheduler.py", line 120, in _run_job
today at 15:22:52    data = runtime.generate(job, params)
today at 15:22:52           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
today at 15:22:52  File "/usr/local/lib/python3.11/site-packages/kernelci/runtime/lava.py", line 225, in generate
today at 15:22:52    raise RuntimeError("Failed to render LAVA job template: " +
today at 15:22:52RuntimeError: Failed to render LAVA job template: 'None' has no attribute
```

**Comment by nuclearcat** [comment]
I guess we are handling exception more properly now and issue can be closed?

**Comment by JenySadadia** [comment]
Yes, I haven't seen this being reproduced.
