### ISSUE TITLE
Some nodes have error_code + pass

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-pipeline#614]
We have some nodes with error_message set and claiming 'pass'
What is possible happened - timeout service set "node_timeout" to node, but then late LAVA results arrived and set "pass".

```
Kernel: 12f30990e9b02966e3742c7c94996d4bae8054c9 - staging-mainline - kernelci
{
    "id": "664f6d9d335faaf8b0444069",
    "kind": "test",
    "name": "baseline-nfs-x86-amd",
    "path": [
        "checkout",
        "kbuild-gcc-10-x86",
        "baseline-nfs-x86-amd"
    ],
    "group": "baseline-nfs-x86-amd",
    "parent": "664f6ad2335faaf8b044315a",
    "state": "done",
    "result": "pass",
    "artifacts": {
        "lava_log": "https://kciapistagingstorage1.file.core.windows.net/staging/baseline-nfs-x86-amd-664f6d9d335faaf8b0444069/log.txt.gz?sv=2022-11-02&ss=f&srt=sco&sp=r&se=2024-10-17T19:19:12Z&st=2023-10-17T11:19:12Z&spr=https&sig=sLmFlvZHXRrZsSGubsDUIvTiv%2BtzgDq6vALfkrtWnv8%3D",
        "callback_data": "https://kciapistagingstorage1.file.core.windows.net/staging/baseline-nfs-x86-amd-664f6d9d335faaf8b0444069/lava_callback.json.gz?sv=2022-11-02&ss=f&srt=sco&sp=r&se=2024-10-17T19:19:12Z&st=2023-10-17T11:19:12Z&spr=https&sig=sLmFlvZHXRrZsSGubsDUIvTiv%2BtzgDq6vALfkrtWnv8%3D"
    },
    "data": {
        "error_code": "node_timeout",
        "error_msg": "Node timed-out",
        "test_source": null,
        "test_revision": null,
        "platform": "hp-14b-na0052xx-zork",
        "device": "hp-14b-na0052xx-zork-cbg-5",
        "runtime": "lava-collabora",
        "job_id": "13979053",
        "job_context": null,
        "regression": null,
        "kernel_revision": {
            "tree": "kernelci",
            "url": "https://github.com/kernelci/linux.git",
            "branch": "staging-mainline",
            "commit": "12f30990e9b02966e3742c7c94996d4bae8054c9",
            "describe": "staging-mainline-20240523.0",
            "version": {
                "version": 6,
                "patchlevel": 9,
                "sublevel": null,
                "extra": "-11953-g12f30990e9b0",
                "name": null
            },
            "patchset": null
        },
        "arch": "x86_64",
        "defconfig": "x86_64_defconfig",
        "config_full": "x86_64_defconfig+x86-board",
        "compiler": "gcc-10",
        "kernel_type": "bzimage"
    },
    "debug": null,
    "jobfilter": null,
    "created": "2024-05-23T16:23:57.230000",
    "updated": "2024-05-23T23:38:59.435000",
    "timeout": "2024-05-23T22:23:57.230000",
    "holdoff": null,
    "owner": "staging.kernelci.org",
    "submitter": "9790c38bd29c1375fc96ed92b9b4bfab",
    "user_groups": []
}
Traceback (most recent call last):
  File "/home/nuclearcat/Documents/KERNELCI-DASHBOARD/./generate_dashboard.py", line 118, in <module>
    main()
  File "/home/nuclearcat/Documents/KERNELCI-DASHBOARD/./generate_dashboard.py", line 113, in main
    process_tree(nodestst, node)
  File "/home/nuclearcat/Documents/KERNELCI-DASHBOARD/./generate_dashboard.py", line 69, in process_tree
    raise Exception(f'Error code: {error_code} on pass result on node: {node["id"]}')
Exception: Error code: node_timeout on pass result on node: 664f6d9d335faaf8b0444069
```

**Comment by JenySadadia** [comment]
The issue has been fixed by https://github.com/kernelci/kernelci-core/pull/2633
