### ISSUE TITLE
`scheduler-docker` service raises an exception

### ISSUE THREAD

**Issue by JenySadadia** [kernelci/kernelci-pipeline#627]
I observed pipeline service `scheduler-docker` raises an exception when we stop it with `docker-compose down`.

```
kernelci-pipeline-scheduler-docker | Traceback (most recent call last):
kernelci-pipeline-scheduler-docker |   File "/home/kernelci/./pipeline/scheduler.py", line 218, in <module>
kernelci-pipeline-scheduler-docker |     status = opts.command(configs, opts)
kernelci-pipeline-scheduler-docker |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
kernelci-pipeline-scheduler-docker |   File "/home/kernelci/./pipeline/scheduler.py", line 211, in __call__
kernelci-pipeline-scheduler-docker |     return Scheduler(configs, args).run()
kernelci-pipeline-scheduler-docker |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kernelci-pipeline-scheduler-docker |   File "/home/kernelci/pipeline/base.py", line 76, in run
kernelci-pipeline-scheduler-docker |     self._stop(context)
kernelci-pipeline-scheduler-docker |   File "/home/kernelci/./pipeline/scheduler.py", line 73, in _stop
kernelci-pipeline-scheduler-docker |     self._cleanup_paths()
kernelci-pipeline-scheduler-docker |   File "/home/kernelci/./pipeline/scheduler.py", line 58, in _cleanup_paths
kernelci-pipeline-scheduler-docker |     job_tmp_dirs = {
kernelci-pipeline-scheduler-docker |                    ^
kernelci-pipeline-scheduler-docker |   File "/home/kernelci/./pipeline/scheduler.py", line 62, in <dictcomp>
kernelci-pipeline-scheduler-docker |     if job.poll() is None
kernelci-pipeline-scheduler-docker |        ^^^^^^^^
kernelci-pipeline-scheduler-docker | AttributeError: 'Container' object has no attribute 'poll'
kernelci-pipeline-scheduler-docker exited with code 1
```

**Comment by JenySadadia** [comment]
The issue doesn't reproduce anymore.
