### ISSUE TITLE
runner.py: Checking git describe test case fails

### ISSUE THREAD

**Issue by JenySadadia** [kernelci/kernelci-pipeline#7]
When running https://github.com/kernelci/kernelci-pipeline/pull/6 code, I am getting below logs:

```
Attaching to trigger, runner, notifier
notifier    | Listening for events...
notifier    | Press Ctrl-C to stop.
runner      | Listening for new checkout events
runner      | Press Ctrl-C to stop.
trigger     | get_node_by_commit_id response []
trigger     | Sending revision node to API: dd81e1c7d5fb126e5fbc5c9e334d7b3ec29a16a0
trigger     | Node id: 61ef9728fd525cf02b33147a
notifier    | Time                        Commit        Status    Name
notifier    | 2022-01-25 06:22:32.483834  dd81e1c7d5fb  Pending   checkout
runner      | Creating node
runner      | obj['revision'] {'tree': 'mainline', 'url': 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git', 'branch': 'master', 'commit': 'dd81e1c7d5fb126e5fbc5c9e334d7b3ec29a16a0', 'describe': None}
runner      | obj['revision'] {'tree': 'mainline', 'url': 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git', 'branch': 'master', 'commit': 'dd81e1c7d5fb126e5fbc5c9e334d7b3ec29a16a0'}
runner      | node {'parent': '61ef9728fd525cf02b33147a', 'name': 'check-describe', 'revision': {'tree': 'mainline', 'url': 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git', 'branch': 'master', 'commit': 'dd81e1c7d5fb126e5fbc5c9e334d7b3ec29a16a0'}}
runner      | Generating job
runner      | tmp: data/tmpwxtb79yw
notifier    | 2022-01-25 06:22:32.504131  dd81e1c7d5fb  Pending   check-describe
runner      | output_file: data/tmpwxtb79yw/check-describe
runner      | Running test
trigger exited with code 0
runner      | Getting Makefile
runner      | https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/plain/Makefile/?id=dd81e1c7d5fb126e5fbc5c9e334d7b3ec29a16a0
runner      | Checking git describe
runner      | Result: FAIL
runner      | 400 Client Error: Bad Request for url: http://172.17.0.1:8001/node
runner      | Traceback (most recent call last):
runner      |   File "/home/kernelci/data/tmpwxtb79yw/check-describe", line 111, in <module>
runner      |     db.submit({'node': node})
runner      |   File "/home/kernelci/.local/lib/python3.10/site-packages/kernelci/data/kernelci_api.py", line 79, in submit
runner      |     raise(ex)
runner      |   File "/home/kernelci/.local/lib/python3.10/site-packages/kernelci/data/kernelci_api.py", line 76, in submit
runner      |     resp = self._post(path, json.dumps(item))
runner      |   File "/home/kernelci/.local/lib/python3.10/site-packages/kernelci/data/kernelci_api.py", line 50, in _post
runner      |     resp.raise_for_status()
runner      |   File "/home/kernelci/.local/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
runner      |     raise HTTPError(http_error_msg, response=self)
runner      | requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://172.17.0.1:8001/node
^CGracefully stopping... (press Ctrl+C again to force)
```

Logs of kernelci-api,
```
INFO:     Application startup complete.

INFO:     172.19.0.1:46588 - "POST /subscribe/node HTTP/1.1" 200 OK

INFO:     172.19.0.1:46602 - "POST /subscribe/node HTTP/1.1" 200 OK

INFO:     172.19.0.1:46612 - "GET /nodes?revision.commit=dd81e1c7d5fb126e5fbc5c9e334d7b3ec29a16a0 HTTP/1.1" 200 OK

post received ----- node id=None kind='node' name='checkout' revision=Revision(tree='mainline', url='https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git', branch='master', commit='dd81e1c7d5fb126e5fbc5c9e334d7b3ec29a16a0', describe=None) parent=None status=None

INFO:     172.19.0.1:46616 - "POST /node HTTP/1.1" 200 OK

INFO:     172.19.0.1:46608 - "GET /listen/187 HTTP/1.1" 200 OK

INFO:     172.19.0.1:46598 - "GET /listen/186 HTTP/1.1" 200 OK

INFO:     172.19.0.1:46624 - "GET /node/61ef9728fd525cf02b33147a HTTP/1.1" 200 OK

INFO:     172.19.0.1:46626 - "GET /node/61ef9728fd525cf02b33147a HTTP/1.1" 200 OK

post received ----- node id=None kind='node' name='check-describe' revision=Revision(tree='mainline', url='https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git', branch='master', commit='dd81e1c7d5fb126e5fbc5c9e334d7b3ec29a16a0', describe=None) parent=ObjectId('61ef9728fd525cf02b33147a') status=None

INFO:     172.19.0.1:46636 - "POST /node HTTP/1.1" 200 OK

INFO:     172.19.0.1:46632 - "GET /listen/186 HTTP/1.1" 200 OK

INFO:     172.19.0.1:46640 - "GET /node/61ef9728fd525cf02b33147b HTTP/1.1" 200 OK

INFO:     172.19.0.1:46648 - "GET /listen/187 HTTP/1.1" 200 OK

INFO:     172.19.0.1:46652 - "GET /node/61ef9728fd525cf02b33147b HTTP/1.1" 200 OK

INFO:     172.19.0.1:46662 - "GET /node/61ef9728fd525cf02b33147b HTTP/1.1" 200 OK

post received ----- node id=ObjectId('61ef9728fd525cf02b33147b') kind='node' name='check-describe' revision=Revision(tree='mainline', url='https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git', branch='master', commit='dd81e1c7d5fb126e5fbc5c9e334d7b3ec29a16a0', describe=None) parent=ObjectId('61ef9728fd525cf02b33147a') status=False

str(e) Object cannot be created with id: 61ef9728fd525cf02b33147b

INFO:     172.19.0.1:46666 - "POST /node HTTP/1.1" 400 Bad Request

INFO:     172.19.0.1:46686 - "POST /unsubscribe/187 HTTP/1.1" 200 OK

INFO:     172.19.0.1:46688 - "POST /unsubscribe/186 HTTP/1.1" 200 OK


```
I have put some debug logs in both the services to print node and exception string.

**Comment by JenySadadia** [comment]
The cause of the issue seems that the last post node request is failing because of the id field in it.
The request should be 'PUT' instead of 'POST' node.
I think https://github.com/kernelci/kernelci-core/pull/979 will resolve the issue.
What do you suggest @gctucker ?

**Comment by gctucker** [comment]
Yes that needs to be fixed now that the other changes for `trigger.py` have been made. I just put a comment about it on #6.

**Comment by JenySadadia** [comment]
@gctucker Please check the comment for this issue: https://github.com/kernelci/kernelci-core/pull/979#issuecomment-1024030576

**Comment by gctucker** [comment]
Yes I've made a fix for that already, will send a PR soon.  Also there were some issues with the implementation of POST / PUT requests in kernelci-core, see https://github.com/kernelci/kernelci-core/pull/1002

**Comment by JenySadadia** [comment]
> Yes I've made a fix for that already, will send a PR soon. Also there were some issues with the implementation of POST / PUT requests in kernelci-core, see [kernelci/kernelci-core#1002](https://github.com/kernelci/kernelci-core/pull/1002)

@gctucker , Could you please push the PR to accommodate changes from https://github.com/kernelci/kernelci-core/pull/979 to the main branch, as I want those changes for test report generation issue ?

**Comment by gctucker** [comment]
I think you mean that the Dockerfile for kernelci-pipeline should be updated to use the kernelci-core main branch? I believe all the required changes have been merged there now, will double check.

**Comment by gctucker** [comment]
Actually this one was also needed, it's merged now: https://github.com/kernelci/kernelci-core/pull/1001

I'll continue to check the `main` branch has everything and then make a PR to update the Dockerfile accordingly.

**Comment by JenySadadia** [comment]
Okay. Thanks.

**Comment by JenySadadia** [comment]
Tested OK on local.
https://github.com/kernelci/kernelci-core/pull/1002/ and https://github.com/kernelci/kernelci-core/pull/1001 fixed the issues.
Should I close the issue? @gctucker

**Comment by gctucker** [comment]
The pull requests should be linked so the issue will get closed when they're merged.

**Comment by gctucker** [comment]
Oh I see, yes the error initially reported here has now been fixed in kernelci-core.  However, #13 needs to be merged in order to produce test results now. I think we can close this current issue and open new ones when needed.
